# Generated by Django 5.1.7 on 2025-06-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0013_maintenancerequest_equipment_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="infrastructure.room",
            ),
        ),
    ]
