# Generated by Django 5.1.7 on 2025-06-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0014_alter_maintenancerequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="infrastructure.block",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"block__code__in": ["A", "B"]},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="infrastructure.floor",
            ),
        ),
    ]
